cross-selling:
  algeria:
  austria:
  belgium:
  canada:
  mexico:
  netherlands:
  romania:
  singapore:
  tunisia:
  ireland:
  lithuania:
  colombia:
  morocco:
  israel:

product-bundle:
  singapore:
  belgium:
  canada:
  colombia:
  ireland:
  lithuania:
  mexico:
  netherlands:

suggested-products:
  algeria:
  austria:
  belgium:
  canada:
  colombia:
  ireland:
  lithuania:
  mexico:
  morocco:
  netherlands:
  romania:
  singapore:
  israel:
